### ISSUE TITLE
Provide return value for the ID of the artifact

### ISSUE THREAD

**Issue by LinqLover** [actions/upload-artifact#200] opened 2021-05-07 19:37 UTC
I am building a workflow where I would like to provide a URL to the uploaded artifact by using [the `artifacts` endpoint of the API](https://docs.github.com/en/rest/reference/actions#get-an-artifact). Unfortunately, at the moment I don't see a way to retrieve the ID of the newly uploaded artifact from the step in order to use it in a later step.

My workaround will be to use the latest artifact ID and hope that it matches the current workflow run, but obviously, this is not an elegant solution.

**Comment by konradpabjan** [comment] 2021-05-14 13:11
Closing as a duplicate of https://github.com/actions/upload-artifact/issues/50

Not currently possible

**Closed by konradpabjan** 2021-05-14 13:11 UTC
Labels: duplicate

**Comment by SanthoshKumar1234** [comment] 2022-10-22 06:36
How can we download the   Github artifact in azure devops pipeline  which uploaded through  the guthub actions
