### ISSUE TITLE
Mac tar archives appear to be corrupted?

### ISSUE THREAD

**Issue by spinicist** [actions/upload-artifact#151] opened 2020-12-01 21:38 UTC
**Describe the bug**

This is not strictly an issue with the upload-artifact action, but an e-mail from Github Support requested that I open an issue here.

Please see here for a full description: https://github.community/t/bizarre-issue-with-tar-archive-for-macos-build/145377

In short, on the Mac machines, the `tar` command produces corrupt output, which leads to corrupt artifacts in my Action. Linux hosts are unaffected. Installing `gnu-tar` via `homebrew` works around the problem, but does not fix it.

By looking back through https://github.com/spinicist/QUIT/actions, this problem seems to have started around 4 months ago. Build 101 from 5 months ago has the correct file size, build 102 from 4 months ago has the incorrect file size for the Mac artifact.

**Version**
- [*] V1
- [ ] V2

**Environment**
- [ ] self-hosted
- [ ] Linux
- [ ] Windows
- [*] Mac

**Run/Repo Url**
Repo: https://github.com/spinicist/QUIT
A previously successful run: https://github.com/spinicist/QUIT/actions/runs/148512381
A corrupt run: https://github.com/spinicist/QUIT/actions/runs/379948077
A run with `gnu-tar` workaround: https://github.com/spinicist/QUIT/actions/runs/385083463

**How to reproduce**

Use the system `tar` in an Action that runs on Mac.

**Comment by mzabaluev** [comment] 2021-02-04 12:30
Should be fixed in https://github.com/actions/virtual-environments/issues/1534, to land in the runners hopefully soon.

**Comment by mzabaluev** [comment] 2021-02-04 21:08
> Should be fixed in actions/virtual-environments#1534, to land in the runners hopefully soon.

Correction: that change is a band-aid since `tar` found in the pristine environment's PATH is still broken.
Filed as https://github.com/actions/virtual-environments/issues/2619

**Comment by spinicist** [comment] 2021-02-04 21:18
Thanks for pushing to fix this properly.

Do you, or does anyone else, know how this started happening? It's such a bizarre issue I can't come up with a plausible explanation and my curiosity won't drop it.

**Comment by mzabaluev** [comment] 2021-02-04 21:25
@spinicist I myself am disturbed so much by it that I'm going to file an issue requesting reproducibility and integrity proof of virtual environment images. If some supposedly honest mistake was allowed to corrupt our build artefacts for months, can we trust GitHub Actions to not admit something downright malicious?

**Comment by e1732a364fed** [comment] 2022-12-15 03:39
我也遇到了这个问题

**Comment by konradpabjan** [comment] 2023-12-15 01:25
Going to close out this issue. It appears this was resolved a while back ago

On a related note we did just release v4 upload-artifact today https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

Uploads overall should be faster and more reliable and we even output a SHA256 value for the upload artifact. This SHA256 value is in the logs but we also plan on adding it to the artifact metadata in the API responses so that it is easier to check artifact integrity

When downloading v1-v3 artifacts from the UI after a run was successful there cases and reports of sometimes artifacts being corrupted (retries would fix it), however with v4 the behavior has changed and the risk of any type of corruption is nonexistent.

**Closed by konradpabjan** 2023-12-15 01:25 UTC
Labels: bug
