### ISSUE TITLE
single file still is wrapped in a zip

### ISSUE THREAD

**Issue by shalom938** [actions/upload-artifact#334] opened 2022-07-03 21:59 UTC
### What happened?

with this i still get my download as a zip wrapping my original zip, i just want that zip.
it did work for a day after upgrading to v3 like the documentation said but then again i get a my zip wrapped. 

      uses: actions/upload-artifact@v3
      with:
        name: digma-intellij-plugin
        path: build/distributions/my-intellij-plugin-0.0.14.zip

### What did you expect to happen?

dowmload link with single file

### How can we reproduce it?

try to upload siingle zip file

### What version of the action are you using?

3

### What are your runner environments?

linux

**Comment by Margen67** [comment] 2022-08-21 03:45
#39

**Comment by konradpabjan** [comment] 2023-12-14 20:31
Closing as a duplicate of https://github.com/actions/upload-artifact/issues/39

**Closed by konradpabjan** 2023-12-14 20:31 UTC
Labels: bug
