### ISSUE TITLE
Cannot access artifacts before the entire workflow has completed

### ISSUE THREAD

**Issue by LinqLover** [actions/upload-artifact#181] opened 2021-03-17 17:13 UTC
**Describe the bug**
Sorry if this limitation has already been reported somewhere else. Some jobs of my workflow have already completed a few minutes ago and according to the logs, their artifacts have been uploaded successfully. Still, I need to wait until the final job completes before I am able to view/download the artifacts from the web view of the job. By the way, the "annotations" section is not visible earlier, too.

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Run/Repo Url**
![image](https://user-images.githubusercontent.com/38782922/111508742-551a8e00-874c-11eb-8962-29bad9deaf0d.png)
![image](https://user-images.githubusercontent.com/38782922/111508799-62d01380-874c-11eb-85df-c57673db8d80.png)
https://github.com/hpi-swa-lab/SqueakByExample-english/actions/runs/661846558

**Comment by konradpabjan** [comment] 2021-03-18 16:08
This is a known limitation. Closing as a duplicate of:  https://github.com/actions/upload-artifact/issues/53

Some more info here: https://github.com/actions/toolkit/issues/379

**Closed by konradpabjan** 2021-03-18 16:08 UTC
Labels: duplicate
