### ISSUE TITLE
This process is way too slow

### ISSUE THREAD

**Issue by u382514** [actions/upload-artifact#199] opened 2021-05-07 03:34 UTC
5 minutes to fix bug, 40 minutes to upload/download artifact. Are there any plans in the works to make this more performant?

**Comment by konradpabjan** [comment] 2021-05-14 15:16
How many files are you uploading? General telemetry indicates that each files takes 100ms to upload with 2 concurrent uploads happening at a time (you can see all this information by turning on [step debugging](https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging) ). Note that uploads from self-hosted runners will be slower. 

If you're uploading hundreds or thousands of files than you can create a zip yourself beforehand using the steps here and upload that: https://github.com/actions/upload-artifact#too-many-uploads-resulting-in-429-responses. That will significantly reduce the amount of HTTP calls and your upload will be much faster. You will have a zip of a zip when you download the artifact unfortunately though until we add the option to download files individually from the UI

**Comment by u382514** [comment] 2021-05-14 19:11
I tried that too. I zipped it up in the build and tried to upload the artifact and that shaved off about 10 minutes of a 150 meg file. So it still took roughly 30 minutes for just the upload/download piece of it. The build, test, zip and subsequent unzip and push to prod only took about 5 minutes of a 35 minute process. For now I just skip the artifact upload/download process and the time to prod is about 5 minutes total. It seems to be consistently slow too as I ran the process numerous times without any real differences to note.

**Comment by BlairMcClelland** [comment] 2022-07-13 01:08
Any update on this? It is painfully slow compared to Azure Pipeline's Pipeline Artifact offering. Uploading 4500~ files / 350~ MB took <30 secs there, while in Github Actions it's taking around 5 minutes 
https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml

**Comment by twz123** [comment] 2022-07-20 11:44
I noticed that actions/cache is nearly an order of magnitude faster than actions/upload-artifact. In my experiments, I found that a single 400 MiB file takes about 150 seconds to upload and 15 seconds to download (with actions/download-artifact). In contrast, putting it into a cache takes 23 seconds, and restoring the cache takes less than 10 seconds.

So the reason for the slowness does not seem to be insufficient network bandwidth on the actions runner side.

**Comment by tamascsaba** [comment] 2022-07-27 10:35
I have the same issue on large amount of files upload and download are also really slow.

**Comment by wind57** [comment] 2022-08-01 10:26
uploading is very different then caching. you might need different artifacts for _each_ build, and caching does not achieve that. Suppose you build docker images - which are unique in each build and need to be shared across other steps, and can not really be cached, unless you hack it:

What we have done is something like this:

```
name: sets environment variables
description: sets environment variables
runs:
  using: "composite"
  steps:
    - name: set env variables
      shell: bash
      run: |
        echo "DOCKER_IMAGES_KEY=$(echo $GITHUB_RUN_ID)" >> $GITHUB_ENV
```

and then later:

```
name: download docker images
description: download docker images
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v2
      with:
        path: /tmp/docker/images
        key: docker-images-cache-${{ env.DOCKER_IMAGES_KEY }}
        restore-keys: docker-images-cache-${{ env.DOCKER_IMAGES_KEY }}
```

Notice the `GITHUB_RUN_ID` usage. Since this one is unique per run, it achieves "upload/download" via caching, and the time went down in our case from 15 minutes to 1 minute.

**Comment by GMNGeoffrey** [comment] 2022-11-17 23:57
I just attempted to upload a large artifact (7.5G) and discovered just how unusably slow this is. I gave up when I became clear it was going to take around an hour to upload. Yeah, that's not going to work. One thing I notice is that it spends the first 5 minutes "starting upload" whatever that means

```
Thu, 17 Nov 2022 22:58:42 GMT With the provided path, there will be 1 file uploaded
Thu, 17 Nov 2022 22:58:42 GMT Starting artifact upload
Thu, 17 Nov 2022 22:58:42 GMT For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Thu, 17 Nov 2022 22:58:42 GMT Artifact name is valid!
Thu, 17 Nov 2022 22:58:42 GMT Container for artifact "full-build-dir.tar.zst" successfully created. Starting upload of file(s)
Thu, 17 Nov 2022 22:58:52 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 22:59:02 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 22:59:12 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 22:59:22 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 22:59:32 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 22:59:42 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 22:59:52 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:00:02 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:00:12 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:00:22 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:00:32 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:00:42 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:00:52 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:01:02 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:01:12 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:01:22 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:01:32 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:01:42 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:01:52 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:02:02 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:02:12 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:02:22 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:02:32 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:02:42 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:02:52 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:03:02 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:03:12 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:03:15 GMT Uploaded /home/runner/work/iree/iree/full-build-dir.tar.zst (0.1%) bytes 0:8388607
Thu, 17 Nov 2022 23:03:17 GMT Uploaded /home/runner/work/iree/iree/full-build-dir.tar.zst (0.2%) bytes 8388608:16777215
Thu, 17 Nov 2022 23:03:19 GMT Uploaded /home/runner/work/iree/iree/full-build-dir.tar.zst (0.3%) bytes 16777216:25165823
Thu, 17 Nov 2022 23:03:22 GMT Uploaded /home/runner/work/iree/iree/full-build-dir.tar.zst (0.4%) bytes 25165824:33554431
```

From https://github.com/iree-org/iree/actions/runs/3492591056/jobs/5846535076

Running with debug mode gives us some more insights:

```
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]Evaluating condition for step: 'Upload artifacts'
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]Evaluating: success()
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]Evaluating success:
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]=> true
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]Result: true
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]Starting: Upload artifacts
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]Loading inputs
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]Evaluating: env.BUILD_DIR_ARCHIVE
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]Evaluating Index:
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]..Evaluating env:
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]..=> Object
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]..Evaluating String:
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]..=> 'BUILD_DIR_ARCHIVE'
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]=> 'full-build-dir.tar.zst'
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]Result: 'full-build-dir.tar.zst'
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]Evaluating: env.BUILD_DIR_ARCHIVE
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]Evaluating Index:
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]..Evaluating env:
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]..=> Object
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]..Evaluating String:
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]..=> 'BUILD_DIR_ARCHIVE'
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]=> 'full-build-dir.tar.zst'
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]Result: 'full-build-dir.tar.zst'
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]Loading env
Thu, 17 Nov 2022 23:24:01 GMT Run actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]followSymbolicLinks 'true'
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]implicitDescendants 'true'
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]omitBrokenSymbolicLinks 'true'
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]followSymbolicLinks 'true'
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]implicitDescendants 'true'
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]omitBrokenSymbolicLinks 'true'
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]Search path '/home/runner/work/iree/iree/full-build-dir.tar.zst'
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]File:/home/runner/work/iree/iree/full-build-dir.tar.zst was found using the provided searchPath
Thu, 17 Nov 2022 23:24:01 GMT With the provided path, there will be 1 file uploaded
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]Root artifact directory is /home/runner/work/iree/iree
Thu, 17 Nov 2022 23:24:01 GMT Starting artifact upload
Thu, 17 Nov 2022 23:24:01 GMT For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Thu, 17 Nov 2022 23:24:01 GMT Artifact name is valid!
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]Artifact Url: https://pipelines.actions.githubusercontent.com/SaXEyjchYvnWH9Rq3qeZEPLXtO1Hv1A8b0nd0VWR5igNiKNAhf/_apis/pipelines/workflows/3492591056/artifacts?api-version=6.0-preview
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]Upload Resource URL: https://pipelines.actions.githubusercontent.com/SaXEyjchYvnWH9Rq3qeZEPLXtO1Hv1A8b0nd0VWR5igNiKNAhf/_apis/resources/Containers/21359059
Thu, 17 Nov 2022 23:24:01 GMT Container for artifact "full-build-dir.tar.zst" successfully created. Starting upload of file(s)
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]File Concurrency: 2, and Chunk Size: 8388608
Thu, 17 Nov 2022 23:24:01 GMT ##[debug]/home/runner/work/iree/iree/full-build-dir.tar.zst is greater than 64k in size. Creating a gzip file on-disk /tmp/tmp-66835-BA3oAMVklNVD to potentially reduce the upload size
Thu, 17 Nov 2022 23:24:10 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:24:20 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:24:30 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:24:40 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:24:50 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:25:00 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:25:10 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:25:20 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:25:30 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:25:40 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:25:50 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:26:01 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:26:10 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:26:20 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:26:30 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:26:40 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:26:51 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:27:00 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:27:10 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:27:21 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:27:31 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:27:40 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:27:50 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:28:00 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:28:10 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:28:20 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:28:27 GMT ##[debug]The gzip file created for /home/runner/work/iree/iree/full-build-dir.tar.zst is smaller than the original file. The file will be uploaded using gzip.
Thu, 17 Nov 2022 23:28:29 GMT Uploaded /home/runner/work/iree/iree/full-build-dir.tar.zst (0.1%) bytes 0:8388607
Thu, 17 Nov 2022 23:28:30 GMT Total file count: 1 ---- Processed file #0 (0.0%)
Thu, 17 Nov 2022 23:28:31 GMT Uploaded /home/runner/work/iree/iree/full-build-dir.tar.zst (0.2%) bytes 8388608:16777215
```

> /home/runner/work/iree/iree/full-build-dir.tar.zst is greater than 64k in size. Creating a gzip file on-disk /tmp/tmp-66835-BA3oAMVklNVD to potentially reduce the upload size

As you can probably tell by the filename, that is not a great idea. I recall reading that the artifact upload did its own gzip compression (although now I can't find where it's mentioned), but when I tried relying on that, the whole thing was even slower. Using parallel zstd is way faster.

But that alone cannot explain the time here. As noted above, caching is way faster, so this can't only be from limited network bandwidth on the VM. These artifacts are going straight to Azure, probably even in the same data center! There's really no excuse for this to be slow. By contrast, when running on my self-hosted runners in GCP, the gcloud upload of approximately this same file takes under a minute (it's a 7.5G build archive, so unfortunately it's going to be somewhat slow no matter what).

I've traced through the code and whatever it's doing in this while loop is the source of the slowness: https://github.com/actions/toolkit/blob/819157bf872a49cfcc085190da73894e7091c83c/packages/artifact/src/internal/upload-http-client.ts#L321. It's uploading each chunk serially, which probably doesn't help, but gcloud does the same thing with parallel composite upload turned off and does it in the aforementioned minute, so I don't think that can be it. It's recomputing the HTTP headers for each chunk and creating a new file stream. Maybe the underlying client has connection pooling, so the former isn't an issue? I don't see it in here: https://github.com/actions/toolkit/blob/main/packages/http-client/src/index.ts#L328, but I'm no typescript or http request expert. Hard to tell without profiling exactly what the cause is, but profiling does seem to be in order.

**Comment by StanlyLife** [comment] 2023-02-07 08:49
I have the same problem with a project of 23MB it takes ages (almost 1h)
![image](https://user-images.githubusercontent.com/13099896/217195974-182f1bca-d017-4b41-9059-e03c4eaf7d3f.png)
![image](https://user-images.githubusercontent.com/13099896/217196052-dd438272-51bd-46ed-baab-e478d2fd0f7f.png)

as mentioned here https://azureossd.github.io/2022/02/07/React-Deployment-on-App-Service-Linux/

> From [Official Documentation](https://github.com/actions/toolkit/blob/master/packages/artifact/docs/additional-information.md#considerations): During upload, each file is uploaded concurrently in 4MB chunks using a separate HTTPS connection per file. Chunked uploads are used so that in the event of a failure, the upload can be retried. If there is an error, a retry will be attempted after a certain period of time.

> Uploading will be generally be faster if there are fewer files that are larger in size vs if there are lots of smaller files. Depending on the types and quantities of files being uploaded, it might be beneficial to separately compress and archive everything into a single archive (using something like tar or zip) before starting and artifact upload to speed things up.

A solution is mentioned in the [article](https://azureossd.github.io/2022/02/07/React-Deployment-on-App-Service-Linux/#:~:text=Upload%20just%20production%20build%20folder%20in)

**Comment by StanlyLife** [comment] 2023-02-08 13:42
> Stuffing many files into archives files will help, but this action is still https://github.com/actions/upload-artifact/issues/199#issuecomment-841447744 https://github.com/actions/upload-artifact/issues/199#issuecomment-1190171851 https://github.com/actions/upload-artifact/issues/199#issuecomment-1319364919 even for single file uploads.

Reduced my deploy time from 2,5 hours to 15 minutes, still not good, but a lot better.

**Comment by m0un10** [comment] 2023-03-15 10:34
This is insanely broken, how can such a small set of files take so long...
<img width="757" alt="Screenshot 2023-03-15 at 8 33 17 pm" src="https://user-images.githubusercontent.com/7553951/225283240-f75dad35-8d0e-4385-ad16-c560995a5165.png">

Lots of drop outs like this
```
Total file count: 36994 ---- Processed file #20114 (54.3%)
An error has been caught http-client index 1, retrying the upload
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
Exponential backoff for retry #1. Waiting for 5291 milliseconds before continuing the upload at offset 0
Finished backoff for retry #1, continuing with upload
Total file count: 36994 ----
```

**Comment by mattgodbolt** [comment] 2023-04-07 15:48
Also seeing really slow upload speed on GHE: we have a ~135MB tar.xz file that takes ~2m30 to upload. Downloading in a later stage takes 11d. Is there some on-the-fly-ZIPfiling we can disable? I don't need my file to be wrapped in a ZIP, and I suspect the attempts to further compress my tarball are what's taking the time.

**Comment by GMNGeoffrey** [comment] 2023-04-21 05:29
We use a GCS storage bucket. We have our own self-hosted runners on gcp and just use `gcloud` directly, but others may find https://github.com/google-github-actions/upload-cloud-storage useful (I think our usage predates the existence of that action, or at least my discovery of it).

**Comment by mattgodbolt** [comment] 2023-04-21 16:13
I just moved to using GCS storage too, pretty easy to set up with `gcloud storage cp` etc steps (we use GHA on-prem; and our runners are on GCP, so this makes sense for us).

**Comment by ascopes** [comment] 2023-04-21 17:04
It is a shame people have to rely on third party services to get a remotely scalable integration for a core behaviour...

**Comment by rasmus-kirk** [comment] 2023-05-24 09:35
> ```yaml
> name: Upload artifact
> description: Wrapper around GitHub's official action, with additional archiving before upload
> 
> # https://github.com/actions/upload-artifact/blob/main/action.yml
> inputs:
>   name:
>     description: Artifact name
>     required: true
>   path:
>     description: A file, directory or wildcard pattern that describes what to upload
>     required: true
>   if-no-files-found:
>     description: >
>       The desired behavior if no files are found using the provided path.
>       Available Options:
>         warn: Output a warning but do not fail the action
>         error: Fail the action with an error message
>         ignore: Do not output any warnings or errors, the action does not fail
>     required: false
>     default: warn
>   retention-days:
>     description: >
>       Duration after which artifact will expire in days. 0 means using default retention.
>       Minimum 1 day.
>       Maximum 90 days unless changed from the repository settings page.
>     required: false
>     default: '0'
> 
> runs:
>   using: composite
>   steps:
>     - name: Archive artifacts
>       run: tar -cvf ${{ inputs.name }}.tar ${{ inputs.path }}
>       shell: bash
> 
>     - name: Upload artifacts
>       uses: actions/upload-artifact@v3
>       with:
>         if-no-files-found: ${{ inputs.if-no-files-found }}
>         name: ${{ inputs.name }}
>         path: ${{ inputs.name }}.tar
>         retention-days: ${{ inputs.retention-days }}
> 
>     - name: Remove archive
>       run: rm -f ${{ inputs.name }}.tar
>       shell: bash
> ```

```yml
name: Upload artifact
description: Wrapper around GitHub's official action, with additional archiving before upload

# https://github.com/actions/upload-artifact/blob/main/action.yml
inputs:
  name:
    description: Artifact name
    required: true
  path:
    description: One or more files, directories or wildcard pattern that describes what to upload
    required: true
  if-no-files-found:
    description: >
      The desired behavior if no files are found using the provided path.
      Available Options:
        warn: Output a warning but do not fail the action
        error: Fail the action with an error message
        ignore: Do not output any warnings or errors, the action does not fail
    required: false
    default: warn
  retention-days:
    description: >
      Duration after which artifact will expire in days. 0 means using default retention.
      Minimum 1 day.
      Maximum 90 days unless changed from the repository settings page.
    required: false
    default: '0'

runs:
  using: composite
  steps:
    - name: Archive artifacts
      run: tar -cvf ${{ inputs.name }}.tar $(echo "${{ inputs.path }}" | tr '\n' ' ')
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: ${{ inputs.if-no-files-found }}
        name: ${{ inputs.name }}
        path: ${{ inputs.name }}.tar
        retention-days: ${{ inputs.retention-days }}

    - name: Remove archive
      run: rm -f ${{ inputs.name }}.tar
      shell: bash
```

This lets you define multiple filepaths instead of just a single one

**Comment by EmilRinggaard-zoetis** [comment] 2023-07-27 14:21
We have artifacts that are between 200 MB and 700 MB, and it's currently taken around 25 minutes to upload the artifacts, at this state, it's useless for us to use..

**Comment by MakotoE** [comment] 2023-08-01 21:43
It makes me wonder why GitHub doesn't prioritize this because they could be saving upwards of half an hour of free runner time per build.

**Comment by noahtallen** [comment] 2023-08-10 00:27
The default behavior should _definitely_ include compression. I was dealing with a 3MB artifact that had a few thousand files. It took around 1-2min to upload. I used tar with gzip and uploaded the archive, and now it takes 1 second.

In other words, in this worst case scenario, it's literally at least **100x worse** than it needs to be. At a minimum the action should have a "compress?" setting which does it for you!

**Comment by m1daz** [comment] 2023-08-19 06:08
I have a codebase with over 80,000 lines of code. It's hopeless for me. >1hr artifact time.

**Comment by davhdavh** [comment] 2023-08-21 08:33
Azure devops pipelines after code change artifact upload: **13sec**
```
Content upload statistics:
Total Content: 805.5 MB
Physical Content Uploaded: 1.3 MB
Logical Content Uploaded: 3.3 MB
Compression Saved: 2.0 MB
Deduplication Saved: 802.2 MB
Number of Chunks Uploaded: 40
Total Number of Chunks: 27,070
```
Azure devops pipelines rerun build upload: **11sec**
```
Content upload statistics:
Total Content: 807.9 MB
Physical Content Uploaded: 0.3 MB
Logical Content Uploaded: 0.5 MB
Compression Saved: 0.3 MB
Deduplication Saved: 807.4 MB
Number of Chunks Uploaded: 7
Total Number of Chunks: 27,117
```
Github actions after code change artifacts: **12m 45sec**
```
Total size of all the files uploaded is 176968486 bytes
The raw size of all the files that were specified for upload is 412447159 bytes
The size of all the files that were uploaded is 176968486 bytes. This takes into account any gzip compression used to reduce the upload size, time and storage
```
Github actions rerun build artifacts upload: **11m 54sec**

Azure does dedup both across builds and inside the same build, compresses uploads, and uploads in chunks.
Github has no dedup inside the build, no dedup across builds, compresses uploads, and does super slow individual file uploads, Absolutely horrendous.

This puts a total stop to our move to github

**Comment by twz123** [comment] 2023-10-05 10:21
I have a gut feeling that this issue might have been addressed in actions/toolkit#1488, so upload speeds might improve whenever actions/upload-artifact@v4 gets released?

**Comment by fregante** [comment] 2023-10-08 09:31
From that issue:

> his PR adds zip creation + upload functionality to the upcoming v2.0.0 version of `@actions/artifact`. This in turn will power new v4 versions of `upload-artifact` and `download-artifact`.

So yes! This will be fixed in upload-artifact@v4 💚

**Comment by tech234a** [comment] 2023-10-19 22:53
I see there is an `actions/upload-artifact@v4-beta` branch that incorporates these changes, but it doesn't seem to be working at the moment. It outputs: `Error: Unable to get the ACTIONS_RESULTS_URL env variable`. Has anyone been able to get this to work?

**Comment by Ansuel** [comment] 2023-10-19 22:54
@tech234a we can only wait... they already implemented the fix just this actions needs to be updated with the new way.

**Comment by prplecake** [comment] 2023-11-16 16:37
![xkcd-compiling-uploading-artifacts](https://github.com/actions/upload-artifact/assets/83595468/a0c033b7-41a9-4801-821f-766bb3fd2fd6)

**Comment by Ansuel** [comment] 2023-12-15 19:46
With v4... From 20 minutes to upload and download 5 gb of artifact to 1.30-2 minutes... Feel good! Thanks a lot for v4.

**Comment by Amerlander** [comment] 2023-12-16 11:46
Up- and download striped down from 5 minutes to 4 – 12 seconds.

**Comment by Ansuel** [comment] 2023-12-16 11:47
I'm noticing timeout and internal error once in a while but I will keep it monitored... Maybe an idea is to introduce some kind of retry?

**Comment by donv** [comment] 2023-12-17 18:36
From one minute to 3-7 seconds.  Thank you!

**Comment by unkcpz** [comment] 2023-12-18 12:27
The v4 improved the perfermance quite a lot, for our workflow from 10min -> 20s! 
However, we noticed some timeout when running the action on self-runner host, but sometimes the workflow passed. There is a breaking change related to the self-hosted runner in https://github.com/actions/toolkit/tree/main/packages/artifact#breaking-changes, what confused me is the workflow not always fail.

**Comment by konradpabjan** [comment] 2023-12-19 15:36
As some have already noticed, v4 is officially out! 😃 https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

Recommend switching over as one of the big improvements we focused on was speed.

![Image](https://github.com/actions/upload-artifact/assets/16109154/5e018d46-2941-4e1d-888f-121986179b62)

From our testing we've seen upload speed increase by up to 98% in worst case scenarios. We'll have a blog post sometime in January with more details + some data.

Here is a random example from one of our runs comparing v3 to v4

![Image](https://github.com/actions/upload-artifact/assets/16109154/56a77fae-a2a9-4f73-956b-785d8bb8eb69)

https://gh.io/artifact-v3-vs-v4

If there are any issue likes timeouts or upload failures then please upon up new issues (there are already a few related to v4) so we can investigate them separately. 

Closing out!

**Closed by konradpabjan** 2023-12-19 15:36 UTC
Labels: bug

**Comment by Rashelalmamun** [comment] 2023-12-23 00:28
![inbound3587638169755839337](https://github.com/actions/upload-artifact/assets/154642717/57656726-26f0-4a51-8359-6fe5de04ad25)

**Comment by miladdastyar77** [comment] 2024-01-20 21:29
[](url)

**Comment by ElvenSpellmaker** [comment] 2024-04-10 18:38
@konradpabjan Any idea when this will come to GHES please? This current client is uploading large artefacts using GHES and v3 is really slow.

**Comment by kronenthaler** [comment] 2024-04-12 06:36
> @konradpabjan Any idea when this will come to GHES please? This current client is uploading large artefacts using GHES and v3 is really slow.

It seems it is in the roadmap for oct-dec this year https://github.com/github/roadmap/issues/930

**Comment by jommeke22f** [comment] 2024-11-23 05:56
> 5 minutes to fix bug, 40 minutes to upload/download artifact. Are there any plans in the works to make this more performant?
> [!NOTE]
> ``

**Comment by ascopes** [comment] 2024-11-23 08:46
@jommeke22f are you using v4?
