### ISSUE TITLE
Artifact link can be returned once upload-artifact called [feat req]

### ISSUE THREAD

**Issue by alperenbelgic** [actions/upload-artifact#291] opened 2022-01-31 14:17 UTC
### What would you like to be added?

I assume `fileContainerResourceUrl` returns a link like : https://github.com/[org]/[repo]/suites/[some_numbers]/artifacts/[some_other_numbers]

I would like this to be usable during the workflow.
 
https://github.com/actions/upload-artifact/blob/87348cee5fefa95e42e9b4804b4d68e130304158/dist/index.js#L4184the 

### Why is this needed?

I push Slack notifications about the results of automated UI tests and also we generate a HTML file containing visuals about the test results, and save it as an artifact. It would be useful to include the link to this file in a slack message. They wouldn't have to visit GH Actions pages.

**Comment by konradpabjan** [comment] 2023-12-14 20:01
Closing as a duplicate of https://github.com/actions/upload-artifact/issues/50

This is currently possible with [v4 that just shipped](https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/) by making an extra API call but we're pretty close to fully supporting this just FYI

**Closed by konradpabjan** 2023-12-14 20:01 UTC
Labels: enhancement
