### ISSUE TITLE
upload-artifact fails with ENXIO on open()

### ISSUE THREAD

**Issue by dcermak** [actions/upload-artifact#86] opened 2020-06-17 13:56 UTC
**Describe the bug**

I am trying to upload temporary state of my test runner when the tests fail. Unfortunately the upload-artifact action fails with a very obscure error: 
```
Run actions/upload-artifact@v2
  with:
    path: test-resources/
With the provided path, there will be 1596 files uploaded
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: ENXIO: no such device or address, open '/home/runner/work/open-build-service-connector/open-build-service-connector/test-resources/repositoryTreeVi'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:120:12
    at FSReqCallback.oncomplete (fs.js:146:23) {
  errno: -6,
  code: 'ENXIO',
  syscall: 'open',
  path: '/home/runner/work/open-build-service-connector/open-build-service-connector/test-resources/repositoryTreeVi'
}
```
(see: https://github.com/SUSE/open-build-service-connector/runs/780590382?check_suite_focus=true)

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Run/Repo Url**
https://github.com/SUSE/open-build-service-connector/runs/780590382?check_suite_focus=true

**How to reproduce**
Not entirely sure how, it happens every time in my repository. I initially thought that it is due to the big files in there (and one of them has invalid permissions as well), but these get deleted in the step before that.

**Comment by konradpabjan** [comment] 2020-07-27 16:42
Hey @dcermak 

Could you check if this error is still happening? I rolled out a fix to a (possibly related?) bug that was caused by symlinks. Not sure if the root cause was the same, but in the symlink issue that was resolved there were also weird things happening with readstreams so it's possible 🤔

**Comment by konradpabjan** [comment] 2020-09-18 19:51
Closing out. If this issue persists, please reopen

**Closed by konradpabjan** 2020-09-18 19:51 UTC
Labels: bug
