### ISSUE TITLE
[bug] Symlinks are preserved by default

### ISSUE THREAD

**Issue by daskol** [actions/upload-artifact#590] opened 2024-08-02 22:42 UTC
### What happened?

Transition from v4.3.4 to v4.3.5 broke regular building pipelines because `actions/upload-artifact` does not derefernce symlink anymore by default and upload symlinks as is but not target files.

See "Upload StarPU libraries" job for details.

- Oringinal pipeline: https://github.com/nntile/nntile/actions/runs/10142088400/job/28040670213
- Broken pipeline: https://github.com/nntile/nntile/actions/runs/10222093470/job/28286024223

### What did you expect to happen?

1. Pipelines are expected to work as before.
2. Symlinks are dereferenced by default.
3. This action providesd special option/flag for (de)referencing symlinks (kind of -L/-l in common POSIX utils).

### How can we reproduce it?

You can fork repo or create pull request and trigger pipeline on push event.

### What version of the action are you using?

v4.3.5 (no issue with the previous v4.3.4)

### What are your runner environments?

linux

**Comment by erick-xanadu** [comment] 2024-08-05 14:10
This also affected us. Thanks @daskol for reporting this issue.

**Comment by cbaeberle** [comment] 2024-08-06 11:18
#589 Seems the same issue.

**Comment by cipolleschi** [comment] 2024-08-06 12:37
Hi there! Riccardo from Meta, working in the React team and taking care of the React Native build pipeline on GH. 
This affected us as well.

**Comment by robherley** [comment] 2024-08-06 14:55
Hey folks, we reverted & released a new version for v4.3.6 to address the regression.

**Comment by sanjacob** [comment] 2024-08-15 11:45
It would be really nice if this behaviour could be opt-in instead.

**Comment by icfaust** [comment] 2024-10-08 07:17
@robherley It seems that from the original issue steps 1. and 2. have been completed

> ### What did you expect to happen?
> 1. Pipelines are expected to work as before.
> 2. Symlinks are dereferenced by default.
> 3. This action providesd special option/flag for (de)referencing symlinks (kind of -L/-l in common POSIX utils).

Is there any timeline for delivery on step 3?

**Comment by robherley** [comment] 2024-10-08 13:26
@icfaust I don't believe we're going to specifically work on (3) at this time, we were only focused on the regression

**Comment by robherley** [comment] 2024-10-08 13:29
@teo-tsirpanis Do you have an example or a minimum way to reproduce?

I've added a [symlink test](https://github.com/actions/upload-artifact/blob/604373da6381bf24206979c74d06a550515601b9/.github/workflows/test.yml#L59) to upload-artifact's workflow, as well as toolkit too.

**Comment by teo-tsirpanis** [comment] 2024-10-08 14:17
@robherley

* [failing run](https://github.com/TileDB-Inc/TileDB-CSharp/actions/runs/11227543765) ([artifact](https://github.com/TileDB-Inc/TileDB-CSharp/actions/runs/11227543765/artifacts/2027180418))
* [succeeding run](https://github.com/TileDB-Inc/TileDB-CSharp/actions/runs/11207657139) ([artifact](https://github.com/TileDB-Inc/TileDB-CSharp/actions/runs/11207657139/artifacts/2021812840))

The job in question is `Build-Native (ubuntu-latest, dev)` and the symlink should be in `lib/libtiledb.so` in artifact `tiledb-native-dev-linux-x86_64`.

**Comment by robherley** [comment] 2024-10-08 14:40
@teo-tsirpanis is it a relative symlink? Could you `ls -la` the contents before it's uploaded?

Looks like this job is failing to `lstat` the file: https://github.com/TileDB-Inc/TileDB-CSharp/actions/runs/11227543765/job/31209939977#step:7:20

```
Warning: ENOENT warning during artifact zip creation. No such file or directory
Error: ENOENT: no such file or directory, lstat 'libtiledb.so.2.27'
``` 

The relative link might not be getting resolved 🤔

**Comment by FreyJo** [comment] 2024-10-08 15:08
We have the same issue including the `lstat` warning.
In our case, the symlink is created via `CMake`s `set_target_properties`, which seems to be good practice.
See https://github.com/acados/qpOASES/pull/2

**Comment by teo-tsirpanis** [comment] 2024-10-08 15:39
It seems to be a relative symlink:

```bash
teo@theodore-tiledb:~/code/TileDB$ ls -la build/Default/tiledb/libtiledb.so
lrwxrwxrwx 1 teo teo 17 Sep 19 03:25 build/Default/tiledb/libtiledb.so -> libtiledb.so.2.27
```

**Comment by robherley** [comment] 2024-10-08 15:57
Okay, I'll look into a fix. For now feel free to pin to 4.4.0 if you are using relative symlinks.

**Comment by robherley** [comment] 2024-10-08 16:56
I made a PR for toolkit, I'll have my team take a look:
- https://github.com/actions/toolkit/pull/1844

@teo-tsirpanis @FreyJo do y'all want to test with the changes? You can try uploading with my branch version:

```yaml
uses: actions/upload-artifact@robherley/v4.4.2
```

**Comment by teo-tsirpanis** [comment] 2024-10-08 18:28
[The workflow succeeded](https://github.com/teo-tsirpanis/TileDB-CSharp/actions/runs/11240178949/job/31248936161), thanks!

**Comment by robherley** [comment] 2024-10-08 18:36
`v4.4.2` is out, `v4` will be updated shortly!

**Comment by robherley** [comment] 2024-10-08 19:18
And `v4` is released with the latest changes 🎉

**Comment by robherley** [comment] 2024-10-09 01:53
`v4` has been temporarily rolled back to `v4.4.1` due to:
- https://github.com/actions/upload-artifact/issues/630

You can still use `v4.4.2` for these symlink changes.

**Closed** 2024-10-16 15:24 UTC
Labels: bug
