### ISSUE TITLE
Temporary/intermediate artifacts

### ISSUE THREAD

**Issue by dlemstra** [actions/upload-artifact#568] opened 2024-05-08 20:55 UTC
### What would you like to be added?

I would like to have support for temporary/intermediate  artifacts. These artifacts would only be available during the pipeline but not end up in the artifacts once the pipeline is completed.

### Why is this needed?

For some projects I create artifacts that are later used as part of another artifact. For me there is no need to have these intermediate artifacts stored. Having binaries from a single build used in two output artifacts will also store the intermediate artifact in the output. And this means that those binaries are now stored three times when we only need them to be stored two times. Maybe storage is not an issue for GitHub but I think it's a waste of disk space to retain those artifacts so I would like an option to prevent those artifacts from being stored in the output of the pipeline.

**Comment by konradpabjan** [comment] 2024-06-27 20:10
Closing as duplicate of https://github.com/actions/upload-artifact/issues/568

**Closed by konradpabjan** 2024-06-27 20:10 UTC
Labels: duplicate, enhancement

**Comment by dlemstra** [comment] 2024-06-27 20:12
@konradpabjan Can you update the reference the duplicate issue?
