### ISSUE TITLE
[bug] Upload Artifacts takes time to finish

### ISSUE THREAD

**Issue by jj-hoegh** [actions/upload-artifact#442] opened 2023-09-25 09:20 UTC
### What happened?

Upload Artifact job using actions/upload-artifact@v3 is now taking 2 hours to upload an artifact that has a size around 300MB. 

<img width="1038" alt="image" src="https://github.com/actions/upload-artifact/assets/114896284/a5defaf7-ae14-45c3-a581-85a47e2691c0">

Few days ago, this only takes 15 - 20 mins and sometimes faster. Aside from this action, all other other action like checkout works fine and process fast.

### What did you expect to happen?

We expect that the upload will be faster same as few days ago and not 2 Hours for 300 MB war files

### How can we reproduce it?

https://github.com/hoegh-autoliners/link/actions/runs/6294607080/job/17086676107

### What version of the action are you using?

v3

### What are your runner environments?

self-hosted

**Comment by StephenHodgson** [comment] 2023-10-02 13:04
Duplicate of https://github.com/actions/upload-artifact/issues/403

**Comment by StephenHodgson** [comment] 2023-10-02 13:05
The real root cause is because it is artificially capped to charge us more on compute

**Comment by konradpabjan** [comment] 2023-12-14 18:05
V4 upload-artifact and download-artifact as been released today: https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

Recommend switching to `@v4`

v1-v3 were not capped artificially in any way. The real reason is because previously all uploads and traffic was first proxied from the runner to our backend service before finally making it to blob storage. This extra hop made uploads slow and it made the performance widely inconsistent. v4 is effectively an entire re-write from scratch that we've been working on for a very long time and it doesn't have the extra hop/proxy that has been plaguing old versions

V4 offers up to 98% faster uploads from our testing

**Closed by konradpabjan** 2023-12-14 18:05 UTC
Labels: bug

**Comment by StephenHodgson** [comment] 2023-12-14 18:14
Whatever the reason, thanks so much for fixing it! My build times pretty much cut in half. Just wish I could get a refund for all those minutes it's been sucking up over the years 😅

**Comment by jssuttles** [comment] 2023-12-21 15:37
V4 is amazing for this! Thank you so much!!! 🎉🎉🎉🎉🎉
