### ISSUE TITLE
[bug] v4 `%` and `#` characters in artifact name causes an Authorization error

### ISSUE THREAD

**Issue by mxcl** [actions/upload-artifact#473] opened 2023-12-15 16:37 UTC
### What happened?

```
With the provided path, there will be 1 file uploaded
Artifact name is valid!
Root directory input is valid!
Beginning upload of artifact content to blob storage
Error: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:16944f58-601e-00a8-6f73-2fe40e000000
Time:2023-12-15T16:27:52.8549708Z
```

https://github.com/pkgxdev/brewkit/actions/runs/7224478547/job/19686074889?pr=225#step:13:77

### What did you expect to happen?

I've wrapped upload/download in composite actions to make new actions with prior versions. Docs don't say this isn't supported so I was expecting it to continue to work.

### How can we reproduce it?

`my-action/action.yml`:

```yaml
runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@v4
      with:
        path: ${{ steps.tar.outputs.path }}
        name: ${{ steps.tar.outputs.name }}
        if-no-files-found: error
```

### What version of the action are you using?

v4.0.0

### What are your runner environments?

linux

**Comment by robherley** [comment] 2023-12-15 18:30
👋 hey @mxcl I took a look into this

At first, I was unable to repro your error with a composite action. However taking a closer look, the issue is actually with the _name_ of your artifact:

From [your logs](https://github.com/pkgxdev/brewkit/actions/runs/7224478547/job/19686074889?pr=225#step:13:77): 
```yaml
  with:
    path: /tmp/tmp.6S8Gsh9LWE/stark.com%2Ffoo%3D2.3.4+linux+x86-64.tar
    name: stark.com%2Ffoo%3D2.3.4+linux+x86-64
```

Can you try a name that doesn't have `%` characters in it? I believe there is a bug with encoding the download URL path parameters from the backend storage, I've filed an internal issue.

**Comment by mxcl** [comment] 2023-12-15 19:08
Thank you @robherley indeed, removing the percents seems to have fixed the problem.

https://github.com/pkgxdev/brewkit/pull/227/checks

I'll leave this ticket open, but feel free to close it as you see fit.

**Comment by robherley** [comment] 2023-12-15 20:04
I'll leave this open until we decide on a resolution for the `%` character. I'll rename the issue for visibility for others

**Comment by konradpabjan** [comment] 2023-12-20 15:08
Just adding that another side effect of this bug could be users seeing the following during download:

> Error: Unable to download artifact(s): Unable to download and extract artifact: Unexpected HTTP response from blob storage: 409 Public access is not permitted on this storage account.`

Originally reported in https://github.com/actions/upload-artifact/issues/486 that I closed out as duplicate

**Comment by jtamsut** [comment] 2023-12-20 21:54
We come across a few instances of artifacts names having special characters and things breaking. We are working on a fix to make our system robust to any artifact name.

**Comment by tonhuisman** [comment] 2023-12-29 18:56
This seems like a bug that should be taken care of ASAP, it doesn't make me feel confident in adopting v4 that this isn't fixed yet. Using `#${{ github.event.number }}` is quite common in pull_request and push runs, as it's the common presentation on the Pull requests tab in the Web UI.

**Comment by robherley** [comment] 2024-01-24 22:41
👋 This is now fixed! Both `%` and `#` characters will no longer cause an issue.

**Closed by robherley** 2024-01-24 22:41 UTC
Labels: bug
