### ISSUE TITLE
[bug] Since actions/upload-artifact@v4 new public artifacts are no longer accessible

### ISSUE THREAD

**Issue by robert-scheck** [actions/upload-artifact#486] opened 2023-12-20 00:50 UTC
### What happened?

Unfortunately, https://github.com/pdftk-java/pdftk-java-container/pull/9 (actions/upload-artifact@v4) uploads new inaccessible public artifacts. These public artifacts are neither accessible using the GitHub web interface when being logged in nor inside of the action itself using actions/download-artifact@v4 (via https://github.com/pdftk-java/pdftk-java-container/pull/10):

> Error: Unable to download artifact(s): Unable to download and extract artifact: Unexpected HTTP response from blob storage: 409 Public access is not permitted on this storage account.

### What did you expect to happen?

Working again like in v3 ;-)

### How can we reproduce it?

See URLs above

### Anything else we need to know?

Oh, and I do have the trashcan icon (that can be used to delete the artifact). So…I don't have enough permissions to access/download my artifact, but enough permissions to delete it?

### What version of the action are you using?

v4

### What are your runner environments?

linux

### Are you on GitHub Enterprise Server? If so, what version?

No

**Comment by konradpabjan** [comment] 2023-12-20 15:03
This is a known bug https://github.com/actions/upload-artifact/issues/473

The artifact upload is fine but then during download we have a bug because of the `#` character in the artifact name

![Image](https://github.com/actions/upload-artifact/assets/16109154/694198ee-f7b1-4b0c-81c5-e9a4f071ecf3)

We're working on a fix right now. Closing out as a duplicate

**Comment by konradpabjan** [comment] 2023-12-20 15:29
Here is the failed run https://github.com/pdftk-java/pdftk-java-container/actions/runs/7269244986

The workflow file that does the upload is this:

![Image](https://github.com/actions/upload-artifact/assets/16109154/9dde983f-3edb-45af-8f65-3b6a75a1d7e4)

This looks similar to https://github.com/actions/upload-artifact/issues/473, I was able to reproduce this by uploading an artifact with the `#` character in the name.

On download during a run with `download-artifact@v4` the following annotation appears:

> Unable to download artifact(s): Unable to download and extract artifact: Unexpected HTTP response from blob storage: 409 Public access is not permitted on this storage account.

If trying to download from the web UI then this happens: 

![Image](https://github.com/actions/upload-artifact/assets/16109154/37cfc553-cc7b-4e18-b6b7-908e2e6a6830)

**Comment by leettaylor** [comment] 2023-12-20 15:48
Don't think it's exclusive to having a `#` in the name as I have it happen with a file simply named `public-dir.zip`

**Comment by jtamsut** [comment] 2023-12-20 18:05
Hey @leettaylor. This is due to the `#` in your artifact name. If you remove that you should be able to upload successfully. We are aware of this issue and are working on a fix.

Going to close this as its a duplicate of #473.

**Closed by jtamsut** 2023-12-20 18:05 UTC
Labels: bug
