### ISSUE TITLE
Failed to upload artifact

### ISSUE THREAD

**Issue by AurevoirXavier** [actions/upload-artifact#270] opened 2021-11-23 06:28 UTC
### What happened?

```
With the provided path, there will be 9 files uploaded
Total file count: 9 ---- Processed file #8 (88.8%)
Error: Unexpected response. Unable to upload chunk to https://pipelines.actions.githubusercontent.com/RsdR9hD0CJVSpVEzXgkUfNMF6Hs6R4uSsdednoJdwMVkSDQUba/_apis/resources/Containers/25801886?itemPath=darwinia-artifact%2Fdarwinia
##### Begin Diagnostic HTTP information #####
Status Code: 400
Status Message: Bad Request
Header Information: {
  "cache-control": "no-store,no-cache",
  "pragma": "no-cache",
  "transfer-encoding": "chunked",
  "content-type": "application/json; charset=utf-8",
  "strict-transport-security": "max-age=2592000",
  "x-tfs-processid": "bf452d3e-d749-4ecc-95ac-c5690fa61b23",
  "activityid": "0b60cfad-b027-4f7e-aacd-4cf90a915e8a",
  "x-tfs-session": "0b60cfad-b027-4f7e-aacd-4cf90a915e8a",
  "x-vss-e2eid": "0b60cfad-b027-4f7e-aacd-4cf90a915e8a",
  "x-vss-senderdeploymentid": "193695a0-0dcd-ade4-f810-b10ad24a9829",
  "x-frame-options": "SAMEORIGIN",
  "x-cache": "CONFIG_NOCACHE",
  "x-msedge-ref": "Ref A: DB637C6A867E4D66B9A9908ED317BA11 Ref B: DM2EDGE0806 Ref C: 2021-11-23T04:47:59Z",
  "date": "Tue, 23 Nov 2021 04:47:59 GMT"
}
###### End Diagnostic HTTP information ######
Warning: Aborting upload for /home/runner/work/darwinia/darwinia/shared/darwinia due to failure
Error: aborting artifact upload
Total size of all the files uploaded is 30886255 bytes
Finished uploading artifact darwinia-artifact. Reported size is 30886255 bytes. There were 1 items that failed to upload
Error: An error was encountered when uploading darwinia-artifact. There were 1 items that failed to upload.
```

https://github.com/darwinia-network/darwinia/runs/4295287117?check_suite_focus=true

### What did you expect to happen?

Upload successful.

### How can we reproduce it?

Not sure.

### What version of the action are you using?

v2

### What are your runner environments?

linux

**Comment by RaenonX** [comment] 2021-12-08 11:23
Pushing up for facing the exact issue

**Comment by hogsy** [comment] 2021-12-08 12:33
Facing same issue here as well. Was working previously on Nov 12th but not now.

**Comment by nealkruis** [comment] 2021-12-08 16:10
We are experiencing the same issue. Re-running the same workflow that was successful yesterday afternoon now gives this error.

Here is the console output for our workflow:

```
With the provided path, there will be 239 files uploaded
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Artifact name is valid!
Container for artifact "Documentation" successfully created. Starting upload of file(s)
Error: Unexpected response. Unable to upload chunk to https://pipelines.actions.githubusercontent.com/LBGUejEleqC7RxTr3UyWYxJku0Fdd5SJ5usIIswpygD84F3Orn/_apis/resources/Containers/20552360?itemPath=Documentation%5C.nojekyll
##### Begin Diagnostic HTTP information #####
Status Code: 400
Status Message: Bad Request
Header Information: {
  "cache-control": "no-store,no-cache",
  "pragma": "no-cache",
  "transfer-encoding": "chunked",
  "content-type": "application/json; charset=utf-8",
  "strict-transport-security": "max-age=2592000",
  "x-tfs-processid": "d30a5c4e-f411-4df8-95b9-61fc28a0da67",
  "activityid": "fa956f57-fb28-4092-9ad8-b45e13bb9cac",
  "x-tfs-session": "fa956f57-fb28-4092-9ad8-b45e13bb9cac",
  "x-vss-e2eid": "fa956f57-fb28-4092-9ad8-b45e13bb9cac",
  "x-vss-senderdeploymentid": "a07ab14e-025a-39c3-8d53-788cd7ce207f",
  "x-frame-options": "SAMEORIGIN",
  "x-cache": "CONFIG_NOCACHE",
  "x-msedge-ref": "Ref A: 63D453FBCDF349A291DB51C9FE5FA48D Ref B: BN3EDGE0910 Ref C: 2021-12-08T15:53:59Z",
  "date": "Wed, 08 Dec 2021 15:53:58 GMT"
}
###### End Diagnostic HTTP information ######
Warning: Aborting upload for D:\a\cse\cse\doc\output\.nojekyll due to failure
Error: aborting artifact upload
Uploaded D:\a\cse\cse\doc\output\.git\objects\pack\pack-6d69e7822794a9552a2be8d89c726e952f225588.pack (9.0%) bytes 0:8388607
Uploaded D:\a\cse\cse\doc\output\.git\objects\pack\pack-6d69e7822794a9552a2be8d89c726e952f225588.pack (18.0%) bytes 8388608:16777215
Uploaded D:\a\cse\cse\doc\output\.git\objects\pack\pack-6d69e7822794a9552a2be8d89c726e952f225588.pack (27.0%) bytes 16777216:25165823
Total file count: 239 ---- Processed file #95 (39.7%)
Uploaded D:\a\cse\cse\doc\output\.git\objects\pack\pack-6d69e7822794a9552a2be8d89c726e952f225588.pack (36.0%) bytes 25165824:33554431
Uploaded D:\a\cse\cse\doc\output\.git\objects\pack\pack-6d69e7822794a9552a2be8d89c726e952f225588.pack (45.1%) bytes 33554432:41943039
Uploaded D:\a\cse\cse\doc\output\.git\objects\pack\pack-6d69e7822794a9552a2be8d89c726e952f225588.pack (54.1%) bytes 41943040:50331647
Uploaded D:\a\cse\cse\doc\output\.git\objects\pack\pack-6d69e7822794a9552a2be8d89c726e952f225588.pack (63.1%) bytes 50331648:58720255
Uploaded D:\a\cse\cse\doc\output\.git\objects\pack\pack-6d69e7822794a9552a2be8d89c726e952f225588.pack (72.1%) bytes 58720256:67108863
Uploaded D:\a\cse\cse\doc\output\.git\objects\pack\pack-6d69e7822794a9552a2be8d89c726e952f225588.pack (81.2%) bytes 67108864:75497471
Uploaded D:\a\cse\cse\doc\output\.git\objects\pack\pack-6d69e7822794a9552a2be8d89c726e952f225588.pack (90.2%) bytes 75497472:83886079
Uploaded D:\a\cse\cse\doc\output\.git\objects\pack\pack-6d69e7822794a9552a2be8d89c726e952f225588.pack (99.2%) bytes 83886080:92274687
Uploaded D:\a\cse\cse\doc\output\.git\objects\pack\pack-6d69e7822794a9552a2be8d89c726e952f225588.pack (100.0%) bytes 92274688:92966490
Total size of all the files uploaded is 93424960 bytes
File upload process has finished. Finalizing the artifact upload
Upload finished. There were 144 items that failed to upload

The raw size of all the files that were specified for upload is 93864848 bytes
The size of all the files that were uploaded is 93424960 bytes. This takes into account any gzip compression used to reduce the upload size, time and storage

Note: The size of downloaded zips can differ significantly from the reported size. For more information see: https://github.com/actions/upload-artifact#zipped-artifact-downloads 

Error: An error was encountered when uploading Documentation. There were 144 items that failed to upload.
```

**Comment by mbeckh** [comment] 2021-12-08 17:54
Same here. Job was working on Dec 4th, 2021, but now fails for no obvious reason, There were no changes to the job itself.

**Comment by nealkruis** [comment] 2021-12-08 18:45
I believe this is a problem introduced in the 2.3.0 release (the timing checks out for us). We pegged our action to 2.2.4 and everything is working again.

The issue in 2.3.0 could be related to artifacts containing local git repository files as indicated in #281.

**Comment by mbeckh** [comment] 2021-12-08 21:20
> I believe this is a problem introduced in the 2.3.0 release 
confirmed. When the action is set to @v2.2.4. the upload is working again. Most recent update to v2.3 should either be fixed or reverted.

**Comment by ertodd-coke** [comment] 2021-12-08 21:26
Had the exact same issue. Worked yesterday. Broken today. Updating to explicitly use 2.2.4 worked perfectly.

**Comment by mbeckh** [comment] 2021-12-08 21:30
The bug could be related to number of files. A Job using @v2 works when uploading only a single file. Jobs uploading multiple files fail. This would also match the description in #281. The failure described there might not be related to .gitkeep being a repository file but just to .gitkeep being the second file.

**Comment by ferpasri** [comment] 2021-12-09 10:05
7/12/2021
```
With the provided path, there will be 10 files uploaded
Total size of all the files uploaded is 88178 bytes
Finished uploading artifact runTestWebdriverCorrectReplay-artifact. Reported size is 88178 bytes. There were 0 items that failed to upload
Artifact runTestWebdriverCorrectReplay-artifact has been successfully uploaded!
```

9/12/2021
```
With the provided path, there will be 10 files uploaded
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Artifact name is valid!
Container for artifact "runTestWebdriverCorrectReplay-artifact" successfully created. Starting upload of file(s)
Error: Unexpected response. Unable to upload chunk to https://pipelines.actions.githubusercontent.com/hSNpHTyyoSrNWdCUbHrGJ2g9yzo1ps3nsvaO3xhmDSTzw7VY15/_apis/resources/Containers/20589002?itemPath=runTestWebdriverCorrectReplay-artifact%5Clogs%5C2021-12-09_09h46m37s_webdriver_replay_sequence_1.log
##### Begin Diagnostic HTTP information #####
Status Code: 400
Status Message: Bad Request
Header Information: {
  "cache-control": "no-store,no-cache",
  "pragma": "no-cache",
  "transfer-encoding": "chunked",
  "content-type": "application/json; charset=utf-8",
  "strict-transport-security": "max-age=2592000",
  "x-tfs-processid": "c56f7c8d-066b-41b2-b2ea-478c2582da7e",
  "activityid": "ea4d0bb8-afaa-42ad-af27-51a1746d7fb0",
  "x-tfs-session": "ea4d0bb8-afaa-42ad-af27-51a1746d7fb0",
  "x-vss-e2eid": "ea4d0bb8-afaa-42ad-af27-51a1746d7fb0",
  "x-vss-senderdeploymentid": "a07ab14e-025a-39c3-8d53-788cd7ce207f",
  "x-frame-options": "SAMEORIGIN",
  "x-cache": "CONFIG_NOCACHE",
  "x-msedge-ref": "Ref A: 6E9DC44168964CB585F4AADAE8C64629 Ref B: BN3EDGE0808 Ref C: 2021-12-09T09:46:57Z",
  "date": "Thu, 09 Dec 2021 09:46:57 GMT"
}
###### End Diagnostic HTTP information ######
Warning: Aborting upload for D:\a\TESTAR_dev\TESTAR_dev\testar\target\install\testar\bin\webdriver_replay\logs\2021-12-09_09h46m37s_webdriver_replay_sequence_1.log due to failure
Error: aborting artifact upload
Total size of all the files uploaded is 898 bytes
File upload process has finished. Finalizing the artifact upload
Upload finished. There were 9 items that failed to upload

The raw size of all the files that were specified for upload is 6083 bytes
The size of all the files that were uploaded is 898 bytes. This takes into account any gzip compression used to reduce the upload size, time and storage

Note: The size of downloaded zips can differ significantly from the reported size. For more information see: https://github.com/actions/upload-artifact#zipped-artifact-downloads 

Error: An error was encountered when uploading runTestWebdriverCorrectReplay-artifact. There were 9 items that failed to upload.
```

**Comment by CAMOBAP** [comment] 2021-12-09 11:39
The same observed in my repo https://github.com/metanorma/packed-mn/runs/4461130168?check_suite_focus=true

```
Error: Unexpected response. Unable to upload chunk to https://pipelines.actions.githubusercontent.com/fck8thqdZQOwD2B7yWZqMBJYVFI6isQAXgAscuBYIS1J0YuqKD/_apis/resources/Containers/15989562?itemPath=site%5Cogc%5Cdocuments%5C14-065r2%5Cdocument.pdf
##### Begin Diagnostic HTTP information #####
Status Code: 400
Status Message: Bad Request
Header Information: {
  "cache-control": "no-store,no-cache",
  "pragma": "no-cache",
  "transfer-encoding": "chunked",
  "content-type": "application/json; charset=utf-8",
  "strict-transport-security": "max-age=2592000",
  "x-tfs-processid": "76798e9d-00af-42f1-8451-3247b6267f4d",
  "activityid": "480a2cb9-814e-4df6-83a4-2046009e6399",
  "x-tfs-session": "480a2cb9-814e-4df6-83a4-2046009e6399",
  "x-vss-e2eid": "480a2cb9-814e-4df6-83a4-2046009e6399",
  "x-vss-senderdeploymentid": "193695a0-0dcd-ade4-f810-b10ad24a9829",
  "x-frame-options": "SAMEORIGIN",
  "x-cache": "CONFIG_NOCACHE",
  "x-msedge-ref": "Ref A: 50379D9BDB4B4FA8854350F008F69714 Ref B: BN3EDGE1005 Ref C: 2021-12-08T18:33:02Z",
  "date": "Wed, 08 Dec 2021 18:33:02 GMT"
}
###### End Diagnostic HTTP information ######
Warning: Aborting upload for D:\a\packed-mn\packed-mn\site\ogc\documents\14-065r2\document.pdf due to failure
Error: aborting artifact upload
Total size of all the files uploaded is 45017313 bytes
File upload process has finished. Finalizing the artifact upload
Upload finished. There were 90 items that failed to upload

The raw size of all the files that were specified for upload is 63250658 bytes
The size of all the files that were uploaded is 45017313 bytes. This takes into account any gzip compression used to reduce the upload size, time and storage

```

**Comment by kwokcb** [comment] 2021-12-09 14:17
Getting the same issue appear for us (https://github.com/autodesk-forks/MaterialX/runs/4462734963?check_suite_focus=true).

This appears this is the common error that comes back from the link given  in the log:

(https://pipelines.actions.githubusercontent.com/hSNpHTyyoSrNWdCUbHrGJ2g9yzo1ps3nsvaO3xhmDSTzw7VY15/_apis/resources/Containers/20589002?itemPath=runTestWebdriverCorrectReplay-artifact%5Clogs%5C2021-12-09_09h46m37s_webdriver_replay_sequence_1.log)

```
{"$id":"1","innerException":null,"message":"The user 'System:PublicAccess;aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
```

**Comment by ricardoboss** [comment] 2021-12-09 15:21
Also happens here: https://github.com/elephox-dev/framework/runs/4471460171?check_suite_focus=true

**Comment by olebhartvigsen** [comment] 2021-12-10 09:36
Same error observed here:

```
Error: Unexpected response. Unable to upload chunk to https://pipelines.actions.githubusercontent.com/GzWTsAc8Tfkk7NAzxC0CrvDFhIPAaUpAFRbZzar8Syjs8JLKSw/_apis/resources/Containers/3142291?itemPath=ASP-app%5CApp_Plugins%5CExercise.css
##### Begin Diagnostic HTTP information #####
Status Code: 400
Status Message: Bad Request
Header Information: {
  "cache-control": "no-store,no-cache",
  "pragma": "no-cache",
  "transfer-encoding": "chunked",
  "content-type": "application/json; charset=utf-8",
  "strict-transport-security": "max-age=2592000",
  "x-tfs-processid": "dbcd0f50-a18e-4b5a-9184-06101c692ab9",
  "activityid": "32445705-393f-4869-91c5-b1a66e43f437",
  "x-tfs-session": "32445705-393f-4869-91c5-b1a66e43f437",
  "x-vss-e2eid": "32445705-393f-4869-91c5-b1a66e43f437",
  "x-vss-senderdeploymentid": "6be79bb9-f6f7-24a7-0b27-e718f2ab4200",
  "x-frame-options": "SAMEORIGIN",
  "x-cache": "CONFIG_NOCACHE",
  "x-msedge-ref": "Ref A: 7B60BF0CB4314C6497D704CAE0154C8F Ref B: PAOEDGE0616 Ref C: 2021-12-10T09:11:05Z",
  "date": "Fri, 10 Dec 2021 09:11:05 GMT"
}
###### End Diagnostic HTTP information ######
```

**Comment by obecker** [comment] 2021-12-10 11:17
I'm running my builds on linux, macos, and windows:
```
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    ...
```
and the above upload error happens only for windows.
https://github.com/obecker/decycle/actions/runs/1560598795

**Comment by astafan8** [comment] 2021-12-10 16:19
seeing similar issue with ``.nojakyll`` file on our repo, https://github.com/QCoDeS/Qcodes/runs/4485121681?check_suite_focus=true. only on Windows build, only recently.

**Comment by CAMOBAP** [comment] 2021-12-10 16:57
I have assumption that it can happens for 0 bytes files

**Comment by mwaddell** [comment] 2021-12-13 22:41
I am seeing the same thing across multiple projects -- any 0kb file fails to upload with a "400" status code error.  The name or location or extension is irrelevant

**Comment by obecker** [comment] 2022-01-10 11:07
This is a duplicate of https://github.com/actions/upload-artifact/issues/281
The issue has been fixed with v2.3.1
https://github.com/actions/upload-artifact/releases/tag/v2.3.1

**Comment by azqa** [comment] 2022-03-17 17:11
The same error is now appearing for v2.3.1, v.2.4.0 and v3.
```{"$id":"1","innerException":null,"message":"The user 'System:PublicAccess;aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}```

**Comment by ronaldtse** [comment] 2022-03-23 06:44
We've just encountered the issue mentioned by @azqa in this particular instance when using `actions/download-artifact`:
https://github.com/metanorma/metanorma-docker/runs/5655561654?check_suite_focus=true

The exact output is:
```
Error: An error occurred while attempting to decompress the response stream
A 200 response code has been received while attempting to download an artifact
```

The corresponding `actions/upload-artifact` action was successful:
https://github.com/metanorma/metanorma-docker/runs/5655460223?check_suite_focus=true

It baffles me that this particular download fails when our other similar jobs have passed. I wonder if this is due to the length of the artifact name; that was the only difference amongst our jobs.

**Comment by maietta** [comment] 2022-03-25 20:18
> The same error is now appearing for v2.3.1, v.2.4.0 and v3. `{"$id":"1","innerException":null,"message":"The user 'System:PublicAccess;aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}`

Same here. Running v3.

**Comment by diogormendes** [comment] 2022-04-01 15:10
Downgraded from v3 to v2, while I'm seeing fewer failures still see those on v2

https://github.com/metabase/metabase/runs/5789943574?check_suite_focus=true

**Comment by patsevanton** [comment] 2022-06-02 06:52
any news?

**Comment by ThatXliner** [comment] 2022-07-17 01:21
https://github.com/ThatXliner/skootils/runs/7374236761?check_suite_focus=true

Does downgrading help? Or is this just flaky

**Comment by Slach** [comment] 2022-07-17 05:36
it looks completelly flaky ;( and github team do nothing for it ;(

**Comment by Slach** [comment] 2022-07-26 15:26
It so annoying ;(
```
##### Begin Diagnostic HTTP information #####
Status Code: 500
Status Message: Internal Server Error
Header Information: {
  "cache-control": "no-store,no-cache",
  "pragma": "no-cache",
  "content-length": "328",
  "content-type": "application/json; charset=utf-8",
  "strict-transport-security": "max-age=2592000",
  "x-tfs-processid": "ce80f462-6227-4099-b13a-2691ba4d46f8",
  "activityid": "c7b49267-dec5-43a4-8bb8-38bc21ede[54](https://github.com/Altinity/clickhouse-backup/runs/7523341325?check_suite_focus=true#step:7:55)5",
  "x-tfs-session": "c7b49267-dec5-43a4-8bb8-38bc21ede545",
  "x-vss-e2eid": "c7b49267-dec5-43a4-8bb8-38bc21ede545",
  "x-vss-senderdeploymentid": "ac98198d-4d34-0364-420d-bafa6e51dce2",
  "x-frame-options": "SAMEORIGIN",
  "x-cache": "CONFIG_NOCACHE",
  "x-msedge-ref": "Ref A: 2A38F24912B94C5491751DB2F61CE290 Ref B: BN3EDGE0[60](https://github.com/Altinity/clickhouse-backup/runs/7523341325?check_suite_focus=true#step:7:61)8 Ref C: 2022-07-26T15:23:07Z",
  "date": "Tue, 26 Jul 2022 15:23:07 GMT"
}
###### End Diagnostic HTTP information ######
Retry limit has been reached for chunk at offset 0 to https://pipelines.actions.githubusercontent.com/0W0Oo4V5fr4j69RPnubz9dnfrpiwnQjnC7Fgl2vDHsTCLsvfZS/_apis/resources/Containers/122[67](https://github.com/Altinity/clickhouse-backup/runs/7523341325?check_suite_focus=true#step:7:68)186?itemPath=testflows-logs-and-reports%2Fclickhouse_backup%2F_instances%2Fclickhouse1%2Flogs%2Flog.log
```

**Comment by curena-contrast** [comment] 2022-09-21 16:23
Just to add another voice, our organization has also been experiencing this issue. It happens intermittently, and also appears to happen more frequently when it must upload multiple chunks.

**Comment by e3b0c442** [comment] 2022-11-15 17:16
Checking in here, also experiencing this with v3 today.

**Comment by NAJ8ry** [comment] 2022-11-17 13:54
I had this problem and the solution for me was to introduce a period of waiting.

```
      - name: Setup the database within Docker
        run: |
          echo 'Starting the db'
          docker-compose -f ./docker_files/docker-compose_dbOnly.yml -p mynameapp up -d
      - name: Sleep for 15 seconds
        run: sleep 15s
        shell: bash
      - name: Unit tests - pytest
        env:
          TEST_POSTGRES: "postgresql://username:password@localhost:5432/test_temp"
          AUTO_TEST: true;
        run: pytest
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: .
```

The code was correct and worked prior to the introduction to docker. 
My guess is that it is linked to having a file locked during the compose that was not released quickly.
This seems really odd but it now works.

**Comment by radiomix** [comment] 2022-11-25 12:22
Getting the same error 
```
Thu, 24 Nov 2022 14:08:18 GMT Uploaded /home/runner/GHA-artifacts/itude-logistics-eyefreight-daemon-13.0.4.0-SNAPSHOT-ebdf88502efd8999cc1726d2ce7c5a4e80ec57c6.war (68.1%) bytes 83886080:92274687
Thu, 24 Nov 2022 14:08:22 GMT Error: Unexpected response. Unable to upload chunk to https://pipelines.actions.githubusercontent.com/ewM82OcgF3U6Derh4jaIiF3VtxJxCC8Y9TMFFTJrXzQC6ahs3q/_apis/resources/Containers/16863834?itemPath=GHA-artifacts%2Fitude-logistics-eyefreight-daemon-13.0.4.0-SNAPSHOT-ebdf88502efd8999cc1726d2ce7c5a4e80ec57c6.war
Thu, 24 Nov 2022 14:08:22 GMT ##### Begin Diagnostic HTTP information #####
Thu, 24 Nov 2022 14:08:22 GMT Status Code: 400
Thu, 24 Nov 2022 14:08:22 GMT Status Message: Bad Request
Thu, 24 Nov 2022 14:08:22 GMT Header Information: {
Thu, 24 Nov 2022 14:08:22 GMT   "cache-control": "no-store,no-cache",
Thu, 24 Nov 2022 14:08:22 GMT   "pragma": "no-cache",
Thu, 24 Nov 2022 14:08:22 GMT   "transfer-encoding": "chunked",
Thu, 24 Nov 2022 14:08:22 GMT   "content-type": "application/json; charset=utf-8",
Thu, 24 Nov 2022 14:08:22 GMT   "strict-transport-security": "max-age=2592000",
Thu, 24 Nov 2022 14:08:22 GMT   "x-tfs-processid": "34cff34f-643b-4b96-89fe-20f88eda1531",
Thu, 24 Nov 2022 14:08:22 GMT   "activityid": "85fc3eca-310f-4852-a3b9-826a06044018",
Thu, 24 Nov 2022 14:08:22 GMT   "x-tfs-session": "85fc3eca-310f-4852-a3b9-826a06044018",
Thu, 24 Nov 2022 14:08:22 GMT   "x-vss-e2eid": "85fc3eca-310f-4852-a3b9-826a06044018",
Thu, 24 Nov 2022 14:08:22 GMT   "x-vss-senderdeploymentid": "6074703f-c195-632a-bd61-21691fc86fa5",
Thu, 24 Nov 2022 14:08:22 GMT   "x-frame-options": "SAMEORIGIN",
Thu, 24 Nov 2022 14:08:22 GMT   "x-cache": "CONFIG_NOCACHE",
Thu, 24 Nov 2022 14:08:22 GMT   "x-msedge-ref": "Ref A: 043F2106A4CC442283158A3B192D8D38 Ref B: SN1EDGE1411 Ref C: 2022-11-24T14:08:22Z",
Thu, 24 Nov 2022 14:08:22 GMT   "date": "Thu, 24 Nov 2022 14:08:21 GMT"
Thu, 24 Nov 2022 14:08:22 GMT }
``` 

with commit https://github.com/actions/upload-artifact/commit/83fd05a356d7e2593de66fc9913b3002723633cb in step `Setup job`:
```
Thu, 24 Nov 2022 13:17:47 GMT Download action repository 'actions/upload-artifact@v3' (SHA:83fd05a356d7e2593de66fc9913b3002723633cb)
```

**Comment by prein** [comment] 2023-04-05 12:38
Can this be caused by parallel (competing?) attempts from jobs running under matrix strategy?

**Comment by Slach** [comment] 2023-06-21 05:14
@prein 
> Can this be caused by parallel (competing?) attempts from jobs running under matrix strategy?
Yes, I have parallel matrix execution
but i try to upload to different name

```yaml
      - name: Upload testflows logs
        uses: actions/upload-artifact@v3
        with:
          name: testflows-logs-and-reports-${{ matrix.clickhouse }}-${{ github.run_id }}
          path: |
            test/testflows/*.log
            test/testflows/*.log.txt
            test/testflows/clickhouse_backup/_instances/**/*.log
            test/testflows/*.html
          retention-days: 7
```
and it doesn't work ;(

**Comment by konradpabjan** [comment] 2023-12-14 21:39
V4 upload-artifact has released today! Recommend switching over.

https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

v4 is a complete rewrite of the artifact actions with a new backend. v1-v3 uploads sometimes would hit 100% or close to 100% and things would just stop and fail due to mysterious reasons. Sometimes there would also be a small amount of transient errors like 500s or 400s that you see. v4 is all around more reliable, simpler and a host of issues described in this issue should no longer happen.

If there are any similar issues with v4 then please open up new issues

**Closed by konradpabjan** 2023-12-14 21:39 UTC
Labels: bug
